"use client";

import React, { useState } from "react";
import { FileText, Copy, Check, Printer, Download, Loader2 } from "lucide-react";

interface PrescriptionProps {
    prescription: string | null;
    isLoading: boolean;
    error: string | null;
}

export default function Prescription({
    prescription,
    isLoading,
    error,
}: PrescriptionProps) {
    const [copied, setCopied] = useState(false);

    const handleCopy = async () => {
        if (prescription) {
            await navigator.clipboard.writeText(prescription);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        }
    };

    const handlePrint = () => {
        const printWindow = window.open("", "_blank");
        if (printWindow && prescription) {
            printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>Prescription - CliniqAI</title>
          <style>
            body {
              font-family: 'Georgia', 'Times New Roman', serif;
              max-width: 800px;
              margin: 40px auto;
              padding: 20px;
              color: #1a1a1a;
              line-height: 1.6;
            }
            h3 { color: #0369a1; border-bottom: 2px solid #e2e8f0; padding-bottom: 4px; margin-top: 20px; }
            table { width: 100%; border-collapse: collapse; margin: 10px 0; }
            th, td { border: 1px solid #d1d5db; padding: 8px 12px; text-align: left; }
            th { background: #f0f9ff; color: #0369a1; }
            hr { margin: 20px 0; border: none; border-top: 1px solid #e2e8f0; }
            .header { text-align: center; margin-bottom: 30px; border-bottom: 3px double #0369a1; padding-bottom: 15px; }
            .header h1 { color: #0369a1; margin-bottom: 5px; }
            .footer { margin-top: 40px; text-align: center; font-size: 0.85em; color: #64748b; }
            @media print { body { margin: 20px; } }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>🏥 Medical Prescription</h1>
            <p style="color:#64748b;">Generated by CliniqAI — ${new Date().toLocaleDateString()}</p>
          </div>
          ${prescription.replace(/### /g, '<h3>').replace(/\n/g, '<br>')}
          <div class="footer">
            <p>This prescription was AI-generated and must be reviewed by the attending physician.</p>
          </div>
        </body>
        </html>
      `);
            printWindow.document.close();
            printWindow.print();
        }
    };

    const handleDownload = () => {
        if (prescription) {
            const blob = new Blob([prescription], { type: "text/markdown" });
            const url = URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = `prescription-${new Date().toISOString().slice(0, 10)}.md`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        }
    };

    // Simple markdown-to-HTML renderer for the prescription
    const renderMarkdown = (text: string) => {
        let html = text
            // Escape HTML first
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;")
            // Headers
            .replace(/^### (.+)$/gm, '<h3>$1</h3>')
            .replace(/^## (.+)$/gm, '<h3>$1</h3>')
            // Bold
            .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
            // Italic
            .replace(/\*(.+?)\*/g, '<em>$1</em>')
            // Tables
            .replace(/^\|(.+)\|$/gm, (match) => {
                const cells = match.split('|').filter(Boolean).map(c => c.trim());
                if (cells.every(c => /^[-:]+$/.test(c))) return ''; // separator row
                const isHeader = false;
                const tag = isHeader ? 'th' : 'td';
                return `<tr>${cells.map(c => `<${tag}>${c}</${tag}>`).join('')}</tr>`;
            })
            // Horizontal rules
            .replace(/^---$/gm, '<hr />')
            // Lists
            .replace(/^- (.+)$/gm, '<li>$1</li>')
            // Line breaks
            .replace(/\n\n/g, '<br /><br />')
            .replace(/\n/g, '<br />');

        // Wrap consecutive <tr> in table
        html = html.replace(/((?:<tr>.+?<\/tr><br \/>?)+)/g, (match) => {
            const cleaned = match.replace(/<br \/>/g, '');
            return `<table class="w-full text-sm border-collapse my-2">${cleaned}</table>`;
        });

        // Wrap consecutive <li> in ul
        html = html.replace(/((?:<li>.+?<\/li><br \/>?)+)/g, (match) => {
            const cleaned = match.replace(/<br \/>/g, '');
            return `<ul class="list-disc pl-5 space-y-1">${cleaned}</ul>`;
        });

        return html;
    };

    return (
        <div className="glass-card p-6 h-full flex flex-col">
            {/* Header */}
            <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2.5">
                    <div className="w-8 h-8 rounded-lg bg-emerald-500/15 flex items-center justify-center">
                        <FileText className="w-4 h-4 text-emerald-400" />
                    </div>
                    <h2 className="text-lg font-semibold text-slate-100">
                        Generated Prescription
                    </h2>
                </div>
                {prescription && (
                    <div className="flex items-center gap-2">
                        <button onClick={handleCopy} className="btn-secondary text-xs" title="Copy">
                            {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
                        </button>
                        <button onClick={handlePrint} className="btn-secondary text-xs" title="Print">
                            <Printer className="w-3.5 h-3.5" />
                        </button>
                        <button onClick={handleDownload} className="btn-secondary text-xs" title="Download">
                            <Download className="w-3.5 h-3.5" />
                        </button>
                    </div>
                )}
            </div>

            {/* Content */}
            <div className="flex-1 overflow-y-auto pr-2 min-h-[200px] max-h-[400px]">
                {isLoading ? (
                    <div className="h-full flex flex-col items-center justify-center gap-4 py-10">
                        <Loader2 className="w-10 h-10 text-sky-400 animate-spin" />
                        <div className="text-center">
                            <p className="text-sm font-medium text-slate-300">
                                Generating prescription...
                            </p>
                            <p className="text-xs mt-1 text-slate-500">
                                Analyzing conversation with AI
                            </p>
                        </div>
                        {/* Loading skeleton */}
                        <div className="w-full space-y-3 mt-4">
                            <div className="skeleton h-4 w-3/4" />
                            <div className="skeleton h-4 w-full" />
                            <div className="skeleton h-4 w-5/6" />
                            <div className="skeleton h-4 w-2/3" />
                        </div>
                    </div>
                ) : error ? (
                    <div className="h-full flex flex-col items-center justify-center gap-3 py-10">
                        <div className="w-12 h-12 rounded-full bg-red-500/10 flex items-center justify-center">
                            <FileText className="w-6 h-6 text-red-400" />
                        </div>
                        <div className="text-center">
                            <p className="text-sm font-medium text-red-300">{error}</p>
                            <p className="text-xs mt-1 text-slate-500">
                                Please try recording again
                            </p>
                        </div>
                    </div>
                ) : prescription ? (
                    <div
                        className="prescription-content fade-in text-sm"
                        dangerouslySetInnerHTML={{ __html: renderMarkdown(prescription) }}
                    />
                ) : (
                    <div className="h-full flex flex-col items-center justify-center text-slate-500 gap-3 py-10">
                        <FileText className="w-10 h-10 opacity-30" />
                        <div className="text-center">
                            <p className="text-sm font-medium">No prescription yet</p>
                            <p className="text-xs mt-1 text-slate-600">
                                Record a conversation and generate a prescription
                            </p>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}
