import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

const PRESCRIPTION_PROMPT = `You are a highly experienced medical AI assistant. Based on the following doctor-patient conversation transcript, generate a structured medical prescription.

IMPORTANT RULES:
1. Extract all relevant medical information from the conversation.
2. If the doctor prescribed specific medications, include them exactly as stated.
3. If certain information is unclear or missing, note it with "[To be confirmed by doctor]".
4. Format the output cleanly with the following sections.
5. Be precise and professional in medical terminology.
6. Do NOT fabricate dosages or medications not mentioned in the conversation.

Generate the prescription in the following format:

### Patient Information
- Name: [if mentioned, otherwise "Not specified"]
- Age: [if mentioned]
- Gender: [if mentioned]

### Chief Complaint
[Main reason for the visit]

### Clinical Findings
[Key observations and symptoms discussed]

### Diagnosis
[Primary and differential diagnoses discussed]

### Medications Prescribed
| # | Medication | Dosage | Frequency | Duration |
|---|-----------|--------|-----------|----------|
[List all medications mentioned]

### Instructions
[Any special instructions, lifestyle advice, or precautions mentioned]

### Follow-up
[Follow-up schedule if mentioned]

---
*This prescription was generated by AI from a conversation transcript and must be reviewed and approved by the attending physician before use.*

TRANSCRIPT:
`;

export async function POST(request: NextRequest) {
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
        return NextResponse.json(
            { error: "Gemini API key not configured. Please set GEMINI_API_KEY in .env.local" },
            { status: 500 }
        );
    }

    try {
        const { transcript } = await request.json();

        if (!transcript || transcript.trim().length === 0) {
            return NextResponse.json(
                { error: "No transcript provided. Please record a conversation first." },
                { status: 400 }
            );
        }

        const genAI = new GoogleGenerativeAI(apiKey);
        const models = ["gemini-2.0-flash", "gemini-2.0-flash-lite", "gemini-2.5-flash"];
        let lastError: unknown = null;

        for (const modelName of models) {
            try {
                console.log(`Trying model: ${modelName}`);
                const model = genAI.getGenerativeModel({ model: modelName });
                const result = await model.generateContent(PRESCRIPTION_PROMPT + transcript);
                const response = await result.response;
                const text = response.text();
                return NextResponse.json({ prescription: text });
            } catch (e) {
                console.error(`Model ${modelName} failed:`, e);
                lastError = e;
                continue;
            }
        }

        // All models failed
        const errorMsg = lastError instanceof Error ? lastError.message : "All models failed";
        const isQuotaError = errorMsg.includes("429") || errorMsg.includes("quota") || errorMsg.includes("Quota");
        return NextResponse.json(
            {
                error: isQuotaError
                    ? "API quota exceeded. Please wait a minute or check your Gemini API key quota at https://aistudio.google.com"
                    : `Failed to generate prescription: ${errorMsg}`
            },
            { status: isQuotaError ? 429 : 500 }
        );
    } catch (error) {
        console.error("Gemini generation error:", error);
        const msg = error instanceof Error ? error.message : "An unexpected error occurred";
        return NextResponse.json(
            { error: `Failed to generate prescription: ${msg}` },
            { status: 500 }
        );
    }
}
